# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 25737210469dde6edce6cffb35029ac05ab33b517cc2b707b2a56b643160870644e9d6aa706ee2e4c92c651a93d070ba4f658cb3f600261c101587bba261bf46

test:
  secret_key_base: e5cc4c63259a39f648352eaf28b3e9e1014ca771ea7ad02927c313572f93c2a55f00a93e517c715d68b4cb3051b1ec7f2a45bf51cf36575d2aa4514ffcfbb49f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
