# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a76a4473e1cbc534ccbd745ca1eba47f45ab84d95100926b1cbd5c54b013a4154405cd7c7e33eb75a4851b781313b36c6e83fd97ef8f0f1e5aa1b73f55f9cce

test:
  secret_key_base: a939fe55c86246631beadb2284708ba62aa2386de729a9449dbcbfd25bc4bdc6d67be3b4f42df0939e996058cda950babbd3629b3097280e00e469ffe39315f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
