# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 29ac84d45c9c6e5d396fd6aca3b9144214bdeb89929701ee0ee65de84f413575a1ba2b0c4be1ffc5d3c1fb1b33ee9a768e90305326ec6221d690864777263d47

test:
  secret_key_base: da0655a8a6575afbc3c948e9e9c9991de45cd537c909ce22e8b4c8d3045a1b76e816957e7127797c08060de6396ee73d0adacf880176abd38cf9eee69b79532b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
