# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27025589daddf5b4e5c26975c6cd5aea3b710acfb3af581f8c9b86833a310db7a4ffc63dd57ce08ead17e5d25a1474154d42f668d97e17e5776be07e3e606144

test:
  secret_key_base: f29ad9f4fba3531ac7e4555e9339aa9b267280422561ad9a81a0e8d3759e285cca1a76cbd261729070064691ed5e713dd3bf8c1d392f81229aea39befe5c7a21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
